image: rust:1.75

default:
  tags:
    - docker
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .target/

stages:
  - build
  - lint
  - deploy

build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - cargo build
  artifacts:
    paths:
      - target/

lint:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - cargo clippy

package:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
  #  needs:
  #    - job: build
  #      artifacts: true
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE/rusters:latest"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build --target final -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

push:
  stage: deploy
  image: docker:24.0.5
  before_script:
    - docker info
  needs:
    - job: package
      artifacts: false
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE/rusters:latest"
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build --target final -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH