image: rust:1.76

default:
  tags:
    - docker

.cache: &cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - target/

stages:
  - build
  - lint
  - deploy

build:
  <<: *cache
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - cargo build
  artifacts:
    paths:
      - target/

lint:
  <<: *cache
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy

push:
  stage: deploy
  image: brqu/docker-az:latest
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    ACR_NAME: "team${TEAM_NAME}${RANDOM_ID}"
  script:
#    - az login --tenant $AZURE_TENANT_ID --service-principal -u $AZURE_CLIENT_ID --federated-token $CI_JOB_JWT_V2
    - az login --tenant $AZURE_TENANT_ID -u $AZURE_USERNAME -p $AZURE_PASSWORD
    - ./deploy-aks-private.sh $TEAM_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
