apiVersion: v1
kind: Service
metadata:
  name: internal
  labels:
    {{- include "rusters.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.30.10.10
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rusters.selectorLabels" . | nindent 4 }}
